version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-iudigital
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  monolito:
    build:
      context: ./monolito
      dockerfile: Dockerfile
    image: shalo09/iudigital-monolito:latest
    container_name: iudigital-monolito
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongodb:27017/iudigital
    depends_on:
      - mongodb

  microservicio-proyectos:
    build:
      context: ./microservicio-proyectos
      dockerfile: Dockerfile
    image: shalo09/iudigital-microservicio:latest
    # container_name: iudigital-microservicio (Eliminado para permitir réplicas)
    environment:
      - PORT=4001
      - MONGO_URI=mongodb://mongodb:27017/iudigital
    deploy:
      replicas: 2 # Escalamiento horizontal: 2 instancias iniciales
    depends_on:
      - mongodb

  nginx-lb:
    image: nginx:latest
    container_name: nginx-load-balancer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "4001:80" # El puerto público 4001 ahora es gestionado por Nginx
    depends_on:
      - microservicio-proyectos

volumes:
  mongodb_data:
